<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WordCatcher.Core\WordCatcher.Core.csproj" />
    <ProjectReference Include="..\WordCatcher.Infrastructure\WordCatcher.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\WordCatcher.ico</ApplicationIcon>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\WordCatcher.ico" />
  </ItemGroup>

</Project>
